---
sidebar: sidebar 
permalink: concept-before-you-begin-to-deploy-gfc.html 
keywords: global file cache, core, edge, management server 
summary: Bevor Sie mit der Implementierung von BlueXP Edge-Caching in der Cloud und an Ihren Remote-Standorten beginnen, müssen Sie viele Anforderungen beachten. 
---
= Bevor Sie mit der Implementierung von BlueXP Edge-Caching beginnen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie mit der Implementierung von BlueXP Edge-Caching in der Cloud und an Ihren Remote-Standorten beginnen, müssen Sie viele Anforderungen beachten.



== Überlegungen zum Edge-Caching mit BlueXP Kerndesign

Je nach Anforderungen müssen Sie möglicherweise eine oder mehrere Core-Instanzen von BlueXP Edge Caching implementieren, um die BlueXP Edge Caching Fabric zu erstellen. Die Core-Instanz wurde entwickelt, um den Datenfluss zwischen Ihren verteilten Edge-Caching-Edge-Instanzen von BlueXP und den Fileserverressourcen im Datacenter zu lenken, beispielsweise Dateifreigaben, Ordner und Dateien.

Wenn Sie Ihre BlueXP Edge Caching-Implementierung entwerfen, müssen Sie ermitteln, was bezüglich Skalierbarkeit, Verfügbarkeit von Ressourcen und Redundanz auf Ihre Umgebung am besten geeignet ist. Der Edge Caching Core von BlueXP kann wie folgt implementiert werden:

* Eigenständige Instanz
* Lastverteiltes Design (Cold Standby)


Siehe <<Richtlinien für die Dimensionierung>> So ermitteln Sie die maximale Anzahl an Edge-Instanzen und die Gesamtanzahl der Benutzer, die jede Konfiguration unterstützen kann:

Wenden Sie sich an Ihren NetApp Solutions Engineer, um mehr über die besten Optionen für Ihre Implementierung in einem Unternehmen zu erfahren.



== Richtlinien für die Dimensionierung

Bei der Konfiguration des ersten Systems sind einige Richtlinien zur Dimensionierung zu beachten. Sie sollten diese Verhältnisse noch einmal überprüfen, nachdem sich einige Verwendungsdaten angesammelt haben, um sicherzustellen, dass Sie das System optimal nutzen. Dazu zählen:

* Verhältnis Kanten/Kern
* Verteiltes Benutzer-/Edge-Verhältnis
* Verhältnis verteilter Benutzer/Kern




=== Anzahl der Edge-Instanzen pro Core-Instanz

Unsere Richtlinien empfehlen bis zu 10 Edge-Instanzen pro BlueXP Edge Caching Core-Instanz mit maximal 20 Edge Cache pro BlueXP Core-Instanz. Dies hängt stark vom Typ und der mittleren Dateigröße des am häufigsten verwendeten Workloads ab. In einigen Fällen können Sie mit den häufigsten Workloads weitere Edge-Instanzen pro Kern hinzufügen. In diesen Fällen sollten Sie sich jedoch an Ihren Account-Vertreter wenden, um zu ermitteln, wie die Anzahl der Edge- und Core-Instanzen in Abhängigkeit von den Typen und Größen der Dateidatensätze korrekt angepasst werden kann.


NOTE: Mehrere Edge Caching Edge- und Core-Instanzen von BlueXP können gleichzeitig genutzt werden, um die Infrastruktur je nach Anforderungen horizontal zu skalieren.



=== Anzahl gleichzeitiger Benutzer pro Edge Instanz

Das Edge Caching von BlueXP Edge bewältigt die Schwerarbeit hinsichtlich Caching-Algorithmen und Unterschiede auf Dateiebene. Eine einzelne Edge-Instanz kann bis zu 500 Benutzer pro dedizierte _physische_ Edge-Instanz und bis zu 300 Benutzer für dedizierte _virtuelle_ Bereitstellungen bedienen. Dies hängt stark vom Typ und der mittleren Dateigröße des am häufigsten verwendeten Workloads ab. Führen Sie bei größeren Dateitypen für Zusammenarbeit bis zu 50 % der maximalen Benutzeranzahl pro BlueXP Edge-Caching Edge-Grenze unter der Grenze (je nach physischer oder virtueller Implementierung) durch. Bei allgemeineren Office-Elementen mit einer mittleren Dateigröße von <1 MB führen Sie zu den 100 %-Benutzern pro Edge-Obergrenze (je nach physischer oder virtueller Bereitstellung).


NOTE: Das Edge Caching von BlueXP erkennt, ob es auf einer virtuellen oder physischen Instanz ausgeführt wird, und begrenzt die Anzahl der SMB-Verbindungen auf die lokale virtuelle Dateifreigabe auf maximal 300 oder 500 gleichzeitige Verbindungen.



=== Anzahl gleichzeitiger Benutzer pro Core-Instanz

Die Edge Caching Core-Instanz von BlueXP ist äußerst skalierbar und bietet eine empfohlene Anzahl an gleichzeitigen Benutzern von 3,000 Benutzern pro Core. Dies hängt stark vom Typ und der mittleren Dateigröße des am häufigsten verwendeten Workloads ab.

Wenden Sie sich an Ihren NetApp Solutions Engineer, um mehr über die besten Optionen für Ihre Implementierung in einem Unternehmen zu erfahren.



== Voraussetzungen

Die in diesem Abschnitt beschriebenen Voraussetzungen gelten für die in der Cloud installierten Komponenten: Den BlueXP Edge Caching Management Server und den BlueXP Edge Caching Core.

Voraussetzungen für das Edge Caching von BlueXP sind unter folgendem Link beschrieben: Download-gfc-Resources.HTML#bluexp-Edge Caching-Edge-Anforderungen[hier].



=== Storage-Plattform (Volumes)

Die Back-End-Storage-Plattform – in diesem Fall sollte Ihre implementierte Cloud Volumes ONTAP-Instanz SMB-Dateifreigaben bereitstellen. Alle Freigaben, die durch BlueXP Edge-Caching offengelegt werden, müssen der Gruppe „Alle“ vollständige Kontrolle auf Share-Ebene ermöglichen und gleichzeitig die Berechtigungen durch NTFS-Berechtigungen einschränken.

Wenn Sie auf der Cloud Volumes ONTAP Instanz nicht mindestens eine SMB-Dateifreigabe eingerichtet haben, müssen Sie die folgenden Informationen bereithalten, damit Sie diese Informationen während der Installation konfigurieren können:

* Active Directory-Domänenname, Name-Server-IP-Adresse, Active Directory-Anmeldedaten.
* Name und Größe des Volumes, das Sie erstellen möchten, sowie Name des Aggregats, auf dem das Volume erstellt wird, und Share-Name.


Wir empfehlen, das Volume so groß wie das gesamte Datenset für die Applikation zu sein, und die Möglichkeit zu einer entsprechend skalierbaren Skalierung bei wachsendem Datensatz. Wenn Sie in der Arbeitsumgebung über mehrere Aggregate verfügen, lesen Sie https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-aggregates.html["Management vorhandener Aggregate"^] Um zu bestimmen, welches Aggregat den meisten verfügbaren Platz für das neue Volume hat.



=== BlueXP Edge Caching Management Server

Der BlueXP Edge Caching Management Server erfordert einen externen Zugriff über HTTPS (TCP Port 443), um eine Verbindung zum Abonnementservice des Cloud-Providers herzustellen und auf diese URLs zuzugreifen:

* \https://gfcproxyforcm-prod.azurewebsites.net/
* \https://rest.zuora.com/v1/subscriptions/
* \https://rest.zuora.com/oauth/token
* \https://talonazuremicroservices.azurewebsites.net
* \https://talonlicensing.table.core.windows.net


Damit dieser Port ordnungsgemäß funktioniert, müssen keine WAN-Optimierungsgeräte oder Richtlinien für Firewall-Einschränkungen für die BlueXP Edge Caching-Software beachtet werden.

Der BlueXP Edge Caching Management Server erfordert außerdem einen eindeutigen (geografischen) NetBIOS-Namen für die Instanz (z. B. GFC-MS1).


NOTE: Ein Management Server kann mehrere BlueXP Edge Caching Core-Instanzen unterstützen, die in verschiedenen Arbeitsumgebungen implementiert werden. Bei der Implementierung über BlueXP verfügt jede Arbeitsumgebung über einen eigenen, separaten Backend-Storage und enthält keine Daten.



=== BlueXP Edge Caching Core

Der BlueXP Edge Caching Core hört auf den TCP-Portbereich 6618-6630. Je nach Ihrer Firewall- oder NSG-Konfiguration müssen Sie möglicherweise den Zugriff auf diese Ports über Inbound Port Rules ausdrücklich zulassen. Zudem müssen diese Ports von WAN-Optimierungs-Geräten und von Firewall-Restriktionen ausgeschlossen werden, damit die Edge Caching Software von BlueXP ordnungsgemäß funktioniert.

Die Hauptanforderungen von BlueXP Edge-Caching sind:

* Ein eindeutiger (geografischer) NetBIOS-Name für die Instanz (z. B. GFC-CORE1)
* Active Directory-Domänenname
+
** Instanzen sollten Ihrer Active Directory-Domäne hinzugefügt werden.
** Instanzen sollten in einer BlueXP Edge Caching Specific Organizational Unit (OU) gemanagt und von vererbten Unternehmens-GPOs ausgeschlossen werden.


* Servicekonto. Die Dienste auf dem Core werden als ein bestimmtes Domain-Benutzerkonto ausgeführt. Dieses Konto, auch als Servicekonto bezeichnet, muss auf jedem der SMB-Server, der mit der Core-Instanz von BlueXP Edge Caching verknüpft wird, die folgenden Berechtigungen besitzen:
+
** Das bereitgestellte Servicekonto muss ein Domänenbenutzer sein.
+
Abhängig von den Einschränkungen und GPOs in der Netzwerkumgebung kann für dieses Konto Administratorrechte für die Domäne erforderlich sein.

** Die IT muss über die Berechtigungen „als Dienst ausführen“ verfügen.
** Das Passwort sollte auf „Never Expire“ gesetzt werden.
** Die Kontooption „Benutzer muss Passwort bei der nächsten Anmeldung ändern“ sollte DEAKTIVIERT werden (deaktiviert).
** Es muss Mitglied der Back-End-Dateiserver-Gruppe sein, die in Backup Operators integriert ist (dies wird automatisch aktiviert, wenn es über BlueXP bereitgestellt wird).






=== Lizenzverwaltungsserver

* Der BlueXP Edge Caching License Management Server (LMS) sollte auf einer Microsoft Windows Server 2016 Standard oder Datacenter Edition oder Windows Server 2019 Standard oder Datacenter Edition konfiguriert werden, vorzugsweise auf der BlueXP Edge Caching Core Instanz im Rechenzentrum oder in der Cloud.
* Wenn Sie eine separate BlueXP Edge Caching-LMS-Instanz benötigen, müssen Sie das neueste Installationspaket für die Edge-Caching-Software von BlueXP auf einer ursprünglichen Microsoft Windows Server-Instanz installieren.
* Die LMS-Instanz muss eine Verbindung zum Abonnementdienst (öffentliches Internet) über HTTPS (TCP-Port 443) herstellen können.
* Die Core- und Edge-Instanzen müssen über HTTPS (TCP-Port 443) eine Verbindung zur LMS-Instanz herstellen.




=== Networking (Externer Zugriff)

Das BlueXP Edge-Caching-LMS erfordert externen Zugriff über HTTPS (TCP Port 443) auf die folgenden URLs.

* Bei Nutzung der abonnementbasierten GFC-Lizenzierung:
+
** \https://rest.zuora.com/v1/subscriptions/<subscription-no>
** \https://rest.zuora.com/oauth/token


* Bei Verwendung der NetApp NSS-basierten Lizenzierung:
+
** \https://login.netapp.com
** \https://login.netapp.com/ms_oauth/oauth2/endpoints
** \https://login.netapp.com/ms_oauth/oauth2/endpoints/oauthservice/tokens


* Wenn Sie eine ältere Lizenzierung von NetApp verwenden:
+
** \https://talonazuremicroservices.azurewebsites.net
** \https://talonlicensing.table.core.windows.net






=== Netzwerkbetrieb

* Firewall: TCP-Ports sollten zwischen BlueXP Edge Caching Edge- und Core-Instanzen zulässig sein.
* BlueXP Edge Caching TCP-Ports: 443 (HTTPS), 6618-6630.
* Geräte zur Netzwerkoptimierung (wie Riverbed Steelhead) müssen so konfiguriert werden, dass sie BlueXP Edge Caching-spezifische Ports durchlaufen (TCP 6618-6630).

