---
sidebar: sidebar 
permalink: download-gfc-resources.html 
keywords: global file cache, edge 
summary: Bevor Sie die BlueXP Edge Caching Edge Software an Ihren Remote-Standorten installieren, müssen Sie viele Anforderungen beachten. 
---
= Bevor Sie mit der Implementierung von Edge Caching Edge-Instanzen von BlueXP beginnen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie die BlueXP Edge Caching Edge Software an Ihren Remote-Standorten installieren, müssen Sie viele Anforderungen beachten.



== Laden Sie die erforderlichen Ressourcen herunter

Laden Sie die virtuellen Vorlagen für Edge Caching von BlueXP herunter, die Sie in Ihren Niederlassungen verwenden möchten, das Software-Installationspaket und zusätzliche Referenzdokumentation:

* Virtuelle Windows Server 2016-Vorlage:
+
https://repo.cloudsync.netapp.com/gfc/2k16-2_3_0-55.zip["Windows Server 2016 .OVA einschließlich NetApp GFC (VMware vSphere 6.5+)"^]
https://repo.cloudsync.netapp.com/gfc/2k16_GFC_2_3_0_55IMAGE.zip["Windows Server 2016 .VHDX einschließlich NetApp GFC (Microsoft Hyper-V)"^]

* Virtuelle Windows Server 2019-Vorlage:
+
https://repo.cloudsync.netapp.com/gfc/2k19-2_3_0-55.zip["Windows Server 2019 .OVA einschließlich NetApp GFC (VMware vSphere 6.5+)"^]
https://repo.cloudsync.netapp.com/gfc/2k19_GFC_2_3_0_55IMAGE.zip["Windows Server 2019 .VHDX einschließlich NetApp GFC (Microsoft Hyper-V)"^]

* BlueXP Edge Caching Edge-Software:
+
https://repo.cloudsync.netapp.com/gfc/GFC-2-3-0-55-Release.exe["NetApp GFC Software Installation Package (EXE)"^]

* Global File Cache Dashboards für Cloud Insights:
+
https://repo.cloudsync.netapp.com/gfc/ci-gfc-dashboards.zip["NetApp GFC Cloud Insights-Dashboards (.ZIP)"]

* Global File Cache-Dokumentation:
+
https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["NetApp Global File Cache User Guide (PDF.Englisch)"^]



link:task-deploy-gfc-edge-instances.html#update-bluexp-edge-caching-edge-software["Auszuführende Schritte"] Für ein Upgrade Ihrer BlueXP Edge Caching Edge-Software.


NOTE: Bei der Bereitstellung von BlueXP Edge Caching auf Windows Server 2016 sollten Sie .NET Framework 4.8 und Windows WebView2 Framework verwenden.



== Entwicklung und Implementierung von Edge Caching mit BlueXP

Je nach Ihren Anforderungen müssen Sie möglicherweise eine oder mehrere Edge-Instanzen basierend auf den gleichzeitigen Benutzersitzungen in einer Zweigstelle bereitstellen. Die Edge-Instanz stellt die virtuelle Dateifreigabe den Endbenutzern in Ihrer Zweigstelle zur Verfügung, die transparent von der zugehörigen Core-Instanz des BlueXP Edge Caching erweitert wurde. Der BlueXP Edge Caching Edge sollte einen enthalten `D:\` NTFS-Volume, das die zwischengespeicherten Dateien innerhalb der Zweigstelle enthält.


NOTE: Beim Edge Caching von BlueXP Edge müssen Sie unbedingt die verstehen link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["Richtlinien für die Dimensionierung"]. Auf diese Weise ist ein korrektes Design für Ihre Edge-Caching-Implementierung von BlueXP möglich. Außerdem müssten Sie herausfinden, welche Aspekte der Skalierbarkeit, der Verfügbarkeit von Ressourcen und Redundanz für Ihre Umgebung am besten geeignet sind.



=== Edge Caching Edge-Instanz von BlueXP

Bei der Implementierung einer Edge Caching Edge-Instanz von BlueXP müssen Sie eine einzelne VM bereitstellen, entweder durch Bereitstellung von Windows Server 2016 Standard, Datacenter Edition, Windows Server 2019 Standard oder Datacenter Edition oder durch Nutzung des Edge Caching `.OVA` Oder `.VHD` Vorlage mit dem gewünschten Windows Server Betriebssystem und der Edge Caching-Software von BlueXP.



==== Schnelle Schritte

. Implementieren Sie die BlueXP Edge Caching Virtual Template, Windows Server 2016 VM, Windows Server 2019 Standard oder Datacenter Edition.
. Stellen Sie sicher, dass die VM mit dem Netzwerk verbunden ist, mit der Domäne verbunden ist und über RDP zugänglich ist.
. Installieren Sie die neueste Edge Caching Edge Software von BlueXP.
. Ermitteln Sie den BlueXP Edge Caching Management Server und die Core-Instanz.
. Konfigurieren Sie die Edge Caching Edge-Instanz von BlueXP.




== Edge-Caching-Anforderungen von BlueXP

Das Edge Caching Edge von BlueXP wurde für alle Plattformen entwickelt, die Windows Server 2016 und 2019 unterstützen. Damit können Remote-Zweigstellen und darüber hinaus eine vereinfachte IT erhalten werden. BlueXP Edge Caching kann in nahezu allen Fällen auf Ihrer vorhandenen Hardware-Infrastruktur, Virtualisierung oder Hybrid/Public Cloud-Umgebungen implementiert werden, wenn sie einige grundlegende Anforderungen erfüllen.

Für den Edge müssen die folgenden Hardware- und Softwareressourcen optimal funktionieren. Weitere Informationen zu den allgemeinen Größenbemessungs-Richtlinien finden Sie unter link:concept-before-you-begin-to-deploy-gfc.html#sizing-guidelines["Richtlinien für die Dimensionierung"].



=== Stabile Server-Appliance

Das BlueXP Edge Caching Installationspaket erstellt eine robuste Software-Appliance auf jeder Microsoft Windows Server-Instanz. _Nicht deinstallieren_ das BlueXP Edge Caching-Paket. Die Deinstallation von BlueXP Edge Caching beeinträchtigt die Funktionalität der Serverinstanz und erfordert möglicherweise eine vollständige Wiederherstellung der Serverinstanz.



=== Physische Hardwareanforderungen

* Mindestens 4 CPU-Kerne
* Mindestens 16 GB RAM
* Dedizierte Single- oder redundante 1-Gbit/s-NIC
* SAS-HDD mit 10.000 U/min oder SSD (bevorzugt)
* RAID-Controller mit Write-Back-Cache-Funktion aktiviert




=== Anforderungen für virtuelle Bereitstellung

Hypervisor-Plattformen sind hinsichtlich des Storage-Subsystems (beispielsweise Latenz) durch eine Performance-Verschlechterung bekannt. Für eine optimale Performance mit BlueXP Edge Caching empfiehlt sich eine physische Serverinstanz mit SSD.

Zusätzlich zu den physischen Host-Anforderungen müssen für eine optimale Performance in virtuellen Umgebungen die folgenden Anforderungen und Ressourcenreservierungen erfüllt werden:

Microsoft Hyper-V 2012 R2 und höher:

* Prozessor (CPU): CPUs müssen als *statisch* gesetzt werden: Minimum: 4 vCPU Cores.
* Arbeitsspeicher (RAM): Mindestens 16 GB als *statisch* eingestellt.
* Festplattenbereitstellung: Festplatten müssen als *feste Festplatte* konfiguriert werden.


VMware vSphere 6.x und höher:

* Prozessor (CPU): Die Reservierung der CPU-Zyklen muss festgelegt werden. Minimum: 4 vCPU Cores @ 10000 MHz.
* Speicher (RAM): Minimum: Reservierung von 16 GB.
* Bereitstellung von Festplatten:
+
** Disk Provisioning muss als *Thick Provisioning Eager Zeroed* eingerichtet werden.
** Festplatten-Shares müssen auf *hoch* gesetzt werden.
** Devices.hotplug muss mit dem vSphere Client auf *False* gesetzt werden, um zu verhindern, dass Microsoft Windows BlueXP Edge Caching-Laufwerke als entfernbar präsentiert.


* Netzwerk: Netzwerkschnittstelle muss auf *VMXNET3* eingestellt sein (kann VM-Tools erfordern).


Der Edge läuft unter Windows Server 2016 und 2019, daher muss die Virtualisierungsplattform das Betriebssystem unterstützen, sowie die Integration mit Dienstprogrammen, die die Performance des Gastbetriebssystems der VM und die Verwaltung der VM, wie beispielsweise VM Tools, verbessern.



=== Anforderungen für die Partitionsgröße

* C:\ - mindestens 250 GB (System-/Boot-Volume)
* D:\ - mindestens 1 TB (separates Datenvolumen für Global File Cache Intelligent File Cache*)


*Die Mindestgröße beträgt 2x der aktive Datensatz. Das Cache-Volume (D:\) kann erweitert werden und wird nur durch die Einschränkungen des Microsoft Windows NTFS-Dateisystems eingeschränkt.



=== Anforderungen an Global File Cache Intelligent File Cache-Festplatten

Die Festplattenlatenz auf der intelligenten File Cache-Festplatte (D:\) von Global File Cache sollte eine durchschnittliche I/O-Plattenlatenz von < 0,5 ms und einen Durchsatz von 1 MiPS pro paralleler Benutzer bieten.

Weitere Informationen finden Sie im https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["NetApp Global File Cache User Guide"^].



=== Netzwerkbetrieb

* Firewall: TCP-Ports sollten zwischen den BlueXP Edge Caching Edge- und dem Management Server- und Core-Instanzen zulässig sein.
+
BlueXP Edge Caching TCP-Ports: 443 (HTTPS – LMS), 6618 – 6630.

* Geräte zur Netzwerkoptimierung (wie Riverbed Steelhead) müssen so konfiguriert werden, dass sie BlueXP Edge Caching-spezifische Ports durchlaufen (TCP 6618-6630).




=== Best Practices für Client-Workstations und Anwendungen

BlueXP Edge-Caching lässt sich transparent in Kundenumgebungen integrieren. Benutzer können über ihre Client-Workstations auf zentralisierte Daten zugreifen und so Enterprise-Applikationen ausführen. Durch das Edge Caching von BlueXP können Sie auf Daten über eine direkte Laufwerkszuordnung oder über einen DFS Namespace zugreifen. Weitere Informationen zu der Edge Caching Fabric von BlueXP, zum intelligenten File Caching und zu wichtigen Aspekten der Software finden Sie im link:concept-before-you-begin-to-deploy-gfc.html["Bevor Sie mit der Implementierung von BlueXP Edge-Caching beginnen"^] Abschnitt.

Um eine optimale Erfahrung und Leistung zu gewährleisten, ist es wichtig, die Anforderungen und Best Practices des Microsoft Windows Clients gemäß dem Benutzerhandbuch für den Global File Cache zu erfüllen. Dies gilt für alle Versionen von Microsoft Windows.

Weitere Informationen finden Sie im https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["NetApp Global File Cache User Guide"^].



=== Best Practices für Firewall und Virenschutz

Während mit BlueXP Edge Caching die Kompatibilität der gängigsten Antiviren-Applikationssuiten mit Global File Cache gewährleistet ist, übernimmt NetApp keine Garantie und übernimmt keine Verantwortung für Inkompatibilitäten oder Performance-Probleme, die durch diese Programme bzw. damit verbundene Updates, Service Packs oder Modifikationen verursacht werden.

NetApp empfiehlt weder die Installation noch die Anwendung von Monitoring- oder Antivirenlösungen auf jeder beliebigen Edge Caching-fähigen Instanz von BlueXP (Core oder Edge). Sollte eine Lösung nach Wahl oder Richtlinie installiert werden, müssen folgende Best Practices und Empfehlungen umgesetzt werden: Allgemeine Virenschutzsuiten finden Sie in Anhang A im https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["NetApp Global File Cache User Guide"^].



=== Firewall-Einstellungen

* Microsoft Firewall:
+
** Behalten Sie die Firewall-Einstellungen als Standard bei.
** Empfehlung: Behalten Sie die Microsoft Firewall-Einstellungen und -Services bei der Standardeinstellung „AUS“ und „nicht gestartet“ für standardmäßige Edge Caching-Instanzen von BlueXP.
** Empfehlung: Belassen Sie die Microsoft Firewall-Einstellungen und -Dienste bei der Standardeinstellung EIN und starten Sie für Edge-Instanzen, die auch die Domain Controller-Rolle ausführen.


* Unternehmens-Firewall:
+
** Die Core-Instanz für das Edge Caching von BlueXP überwacht TCP-Ports 6618-6630 und stellt sicher, dass sich Edge Caching von BlueXP mit diesen TCP Ports verbinden kann.
** BlueXP Edge-Caching-Instanzen erfordern Kommunikation mit dem BlueXP Edge Caching-Managementserver über TCP Port 443 (HTTPS).


* Lösungen/Geräte zur Netzwerkoptimierung müssen so konfiguriert werden, dass sie bestimmte Ports für das Edge Caching von BlueXP durchlaufen.




=== Best Practices für Antiviren-Software

NetApp hat die am häufigsten verwendeten Virenschutzprodukte getestet, darunter Cylance, McAfee, Symantec, Sophos, Trend Micro, Kaspersky, Crowd Strike, Cisco AMP, Tannium und Windows Defender zur Verwendung in Verbindung mit BlueXP Edge Caching. Die Virenschutz-Software sollte von NetApp zertifiziert werden und wird nur unterstützt, wenn sie mit der korrekten Ausschlussliste konfiguriert ist. Siehe Anhang A im https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["NetApp Global File Cache User Guide"^]


NOTE: Das Hinzufügen von Antivirenprogrammen zu einer Edge Appliance kann zu einer Beeinträchtigung der Benutzerleistung um 10 bis 20 % führen.

Weitere Informationen finden Sie im https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["NetApp Global File Cache User Guide"^].



==== Konfigurationsausschlüsse

Antivirus-Software oder andere Indexierung oder Scan-Dienstprogramme von Drittanbietern sollten niemals Laufwerk D:\ auf der Edge-Instanz scannen. Diese Scans des Edge Server-Laufwerks D:\ führen zu zahlreichen offenen Datei-Anfragen für den gesamten Cache-Namespace. Dadurch werden Dateiabholungen über das WAN auf alle Dateiserver im Rechenzentrum optimiert. Eine Überflutung der WAN-Verbindung und eine unnötige Belastung der Edge-Instanz führen zu Leistungseinbußen.

Neben dem Laufwerk D:\ sollten das folgende Edge Caching-Verzeichnis und die folgenden Prozesse von BlueXP generell von allen Virenschutzanwendungen ausgeschlossen werden:

* `C:\Program Files\TalonFAST\`
* `C:\Program Files\TalonFAST\Bin\LMClientService.exe`
* `C:\Program Files\TalonFAST\Bin\LMServerService.exe`
* `C:\Program Files\TalonFAST\Bin\Optimus.exe`
* `C:\Program Files\TalonFAST\Bin\tafsexport.exe`
* `C:\Program Files\TalonFAST\Bin\tafsutils.exe`
* `C:\Program Files\TalonFAST\Bin\tapp.exe`
* `C:\Program Files\TalonFAST\Bin\TappN.exe`
* `C:\Program Files\TalonFAST\Bin\FTLSummaryGenerator.exe`
* 'C:\Programme\TalonFAST\bin\GfcCIAgentService.exe'
* `C:\Program Files\TalonFAST\Bin\RFASTSetupWizard.exe`
* `C:\Program Files\TalonFAST\Bin\TService.exe`
* `C:\Program Files\TalonFAST\Bin\tum.exe`
* `C:\Program Files\TalonFAST\FastDebugLogs\`
* `C:\Windows\System32\drivers\tfast.sys`
* `\\?\TafsMtPt:\` Oder `\\?\TafsMtPt*`
* `\Device\TalonCacheFS\`
* `\\?\GLOBALROOT\Device\TalonCacheFS\`
* `\\?\GLOBALROOT\Device\TalonCacheFS\*`




== NetApp Support-Richtlinie

Die Edge-Caching-Instanzen von BlueXP wurden speziell als primäre Applikation auf einer Windows Server 2016 und 2019 Plattform konzipiert. Edge Caching von BlueXP erfordert bevorzugten Zugriff auf Plattformressourcen, z. B. Festplatten, Arbeitsspeicher, Netzwerkschnittstellen Und kann hohe Anforderungen an diese Ressourcen stellen. Für virtuelle Bereitstellungen sind Arbeitsspeicher-/CPU-Reservierungen und hochperformante Festplatten erforderlich.

* Bei Implementierungen von Zweigstellen sind unterstützte Services und Applikationen auf dem Server mit BlueXP Edge-Caching auf folgende beschränkt:
+
** DNS/DHCP
** Active Directory Domain Controller (BlueXP Edge Caching muss sich auf einem separaten Volume befinden)
** Druckservices
** Microsoft System Center Configuration Manager (SCCM)
** BlueXP Edge-Caching – genehmigte Client-seitige Systemagenten und Virenschutzapplikationen


* NetApp Support und Wartung gilt nur für das Edge-Caching von BlueXP.
* Eine Line-of-Business-Produktivitätssoftware, die normalerweise ressourcenintensiv sind, z. B. Datenbankserver, Mail-Server usw. Werden nicht unterstützt.
* Der Kunde ist für alle Edge-Caching-Software zuständig, die nicht aus BlueXP besteht. Diese könnte auf dem Server installiert werden, auf dem BlueXP Edge Caching ausgeführt wird:
+
** Falls Softwarepakete von Drittanbietern zu Software- oder Ressourcenkonflikten mit dem Edge Caching von BlueXP oder einer kompromittierten Performance führen, muss der Kunde unter Umständen die Software vom Server deaktivieren oder entfernen, auf dem BlueXP Edge Caching ausgeführt wird.
** Der Kunde ist für alle Installationen, Integrationen, Support und Upgrades von Software verantwortlich, die zum Server mit der Edge-Caching-Applikation BlueXP hinzugefügt wurden.


* System Management Utilities/Agents wie Antivirus-Tools und Lizenzagenten können möglicherweise koexistieren. Mit Ausnahme der oben aufgeführten unterstützten Services und Applikationen werden diese Applikationen jedoch nicht durch BlueXP Edge Caching unterstützt, und es müssen weiterhin die gleichen Richtlinien wie oben befolgt werden:
+
** Der Kunde ist für alle Installationen, Integrationen, Support und Upgrades hinzugefügter Software verantwortlich.
** Wenn ein Kunde Softwarepakete von Drittanbietern installiert, durch die Software- oder Ressourcenkonflikte mit dem Edge Caching von BlueXP verursacht oder deren Performance beeinträchtigt werden oder dies vermutlich der Fall ist, kann es möglicherweise erforderlich sein, dass die Support-Abteilung von BlueXP Edge Caching die Software deaktiviert/entfernt.



