---
settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP Edge-Caching-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Probleme wurden behoben
      url: "/fixed-issues.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr 端ber BlueXP Edge-Caching
      url: "/concept-gfc.html"
    - title: Voraussetzungen f端r das Edge Caching von BlueXP
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Implementieren und lizenzieren Sie BlueXP Edge-Caching
      url: "/task-gfc-getting-started.html"
    - title: Voraussetzungen f端r das Edge Caching von BlueXP
      url: "/download-gfc-resources.html"
    - title: BlueXP Edge Caching implementieren
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Verwenden Sie BlueXP Edge-Caching
    entries:
    - title: Endbenutzerschulung
      url: "/concept-gfc-enduser-training.html"
    - title: Weitere Informationen
      url: "/reference-gfc-additional-information.html"
  - title: Wissen und Support
    entries:
    - title: F端r den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
