---
settings:
  name: BlueXP edge caching
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: BlueXP Edge-Caching-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Probleme wurden behoben
      url: "/fixed-issues.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über BlueXP Edge-Caching
      url: "/concept-gfc.html"
    - title: Voraussetzungen für das Edge Caching von BlueXP
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Implementieren und lizenzieren Sie BlueXP Edge-Caching
      url: "/task-gfc-getting-started.html"
    - title: Voraussetzungen für das Edge Caching von BlueXP
      url: "/download-gfc-resources.html"
    - title: BlueXP Edge Caching implementieren
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Verwenden Sie BlueXP Edge-Caching
    entries:
    - title: Endbenutzerschulung
      url: "/concept-gfc-enduser-training.html"
    - title: Weitere Informationen
      url: "/reference-gfc-additional-information.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Erfahren Sie mehr über BlueXP Edge-Caching
      url: concept-gfc.html
    - title: Was ist neu
      url: whats-new.html
    - title: Einschränkungen
      url: concept-gfc.html#limitations
  - title: Implementierung von Komponenten
    links:
    - title: Implementieren Sie Cloud Volumes ONTAP als Storage-Plattform
      url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
    - title: Implementieren Sie den BlueXP Edge Caching Management Server und Core
      url: task-gfc-getting-started.html#enable-bluexp-edge caching-in-your-working-environment
    - title: Edge Caching von Edge-Instanzen von BlueXP implementieren
      url: task-deploy-gfc-edge-instances.html
  - title: Benutzer Schulen
    links:
    - title: Endbenutzerschulung
      url: concept-gfc-enduser-training.html
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: BlueXP-Blog
      url: https://bluexp.netapp.com/blog
    - title: Cloud-Webinare
      url: https://bluexp.netapp.com/events
  - title: Andere Ressourcen
    links:
    - title: BlueXP Edge Caching – Anwendungsfälle
      url: https://bluexp.netapp.com/global-file-cache
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
