---
sidebar: sidebar 
permalink: reference-gfc-additional-information.html 
keywords: global file cache 
summary: Über die folgenden Links erhalten Sie weitere Informationen zu BlueXP Edge Caching und anderen NetApp Produkten. 
---
= Weitere Informationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Unter den folgenden Links erhalten Sie weitere Informationen zu BlueXP Edge Caching und anderen NetApp Produkten:

* BlueXP Edge-Caching – FAQ
+
** Sehen Sie sich eine Liste mit häufig gestellten Fragen und Antworten an https://bluexp.netapp.com/global-file-cache-faq["Hier"^]


* https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.3.0%20User%20Guide.pdf["Benutzerhandbuch Für Global File Cache"^]
* NetApp Produktdokumentation
+
** Siehe zusätzliche Dokumentation für NetApp Cloud-Produkte https://docs.netapp.com/us-en/cloud/["Hier"^]
** Siehe zusätzliche Dokumentation für alle NetApp Produkte https://www.netapp.com/support-and-training/documentation/["Hier"^]


* Die folgenden Kanäle bieten Kunden-Support für Nutzer von BlueXP Edge Caching mit Cloud Volumes ONTAP:
+
** Geführte Problemlösung, Case-Management, Knowledgebase, Downloads, Tools, Und weitere gehen https://bluexp.netapp.com/gfc-support["Hier"^]
** Melden Sie sich beim NetApp Support unter an https://mysupport.netapp.com[] Mit Ihren NSS-Anmeldedaten
** Sofortige Unterstützung für P1-Fehler: +1 856.481.3990 (Option 2)


* Der Kundensupport für Edge-Caching-Benutzer von BlueXP, die Cloud Volumes Services und Azure NetApp Files nutzen, ist durch den Standardsupport von Ihrem Provider erhältlich. Wenden Sie sich an den Google-Kundendienst bzw. den Microsoft-Kundendienst.

